# Generated by Django 5.2.7 on 2025-11-14 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0002_populate_statuses'),
        ('references', '0002_baselbusinessline_baseleventtype_businessprocess_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='MeasureEditableField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.role')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measures.measurestatusref')),
            ],
            options={
                'verbose_name': 'Editable Measure Field',
                'unique_together': {('status', 'role', 'field_name')},
            },
        ),
    ]
