# Generated by Django 5.2.7 on 2025-10-31 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0002_baselbusinessline_baseleventtype_businessprocess_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('INCIDENT', 'Incident'), ('MEASURE', 'Measure'), ('KRI', 'Key Risk Indicator')], max_length=20)),
                ('entity_id', models.IntegerField()),
                ('event_type', models.CharField(choices=[('ROUTING_NOTIFY', 'Routing Notification'), ('INCIDENT_OVERDUE', 'Incident Overdue'), ('MEASURE_OVERDUE', 'Measure Overdue'), ('KRI_OVERDUE', 'KRI Overdue'), ('CUSTOM', 'Custom')], max_length=50)),
                ('sla_stage', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('REVIEW', 'Review'), ('VALIDATION', 'Validation')], max_length=20, null=True)),
                ('routing_rule_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('method', models.CharField(choices=[('SYSTEM', 'System (in-app)'), ('EMAIL', 'Email'), ('SLACK', 'Slack'), ('WEBHOOK', 'Webhook')], default='SYSTEM', max_length=30)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='queued', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='references.role')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_app_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('entity_type', 'entity_id', 'event_type', 'sla_stage', 'recipient', 'recipient_role'), name='ux_notifications_active'),
        ),
        migrations.AlterUniqueTogether(
            name='usernotification',
            unique_together={('notification', 'user')},
        ),
    ]
