# Generated by Django 5.2.7 on 2025-11-01 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('references', '0002_baselbusinessline_baseleventtype_businessprocess_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='ux_notifications_active',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='requires_action',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='entity_type',
            field=models.CharField(choices=[('INCIDENT', 'Incident'), ('MEASURE', 'Measure'), ('KRI', 'Key Risk Indicator')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient_role',
            field=models.ForeignKey(blank=True, help_text='Notification is intended for this role(audit).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.role'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sla_stage',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('REVIEW', 'Review'), ('VALIDATION', 'Validation')], max_length=30, null=True),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('entity_type', 'entity_id', 'event_type', 'sla_stage', 'recipient_role'), name='ux_notifications_active'),
        ),
    ]
