# Generated by Django 5.2.7 on 2025-10-15 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0002_baselbusinessline_baseleventtype_businessprocess_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentStatusRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Incident Status',
                'verbose_name_plural': 'Incident Statuses',
            },
        ),
        migrations.CreateModel(
            name='LossCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Loss Causes',
            },
        ),
        migrations.CreateModel(
            name='SimplifiedEventTypeRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_desc', models.TextField()),
                ('front_end_hint', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Simplified Event Type',
                'verbose_name_plural': 'Simplified Event Types',
            },
        ),
        migrations.CreateModel(
            name='SlaConfig',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('value_int', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('discovered_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('draft_due_at', models.DateTimeField(blank=True, null=True)),
                ('review_due_at', models.DateTimeField(blank=True, null=True)),
                ('validation_due_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('gross_loss_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('recovery_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_loss_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency_code', models.CharField(blank=True, max_length=3, null=True)),
                ('near_miss', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('basel_business_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='references.baselbusinessline')),
                ('basel_event_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='references.baseleventtype')),
                ('business_process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='references.businessprocess')),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='references.businessunit')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_incidents', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_incidents', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='references.product')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validated_incidents', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='incidents.incidentstatusref')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncidentRoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicate', models.JSONField()),
                ('priority', models.IntegerField(default=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('route_to_bu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='references.businessunit')),
                ('route_to_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='references.role')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.incident')),
                ('loss_cause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.losscause')),
            ],
            options={
                'unique_together': {('incident', 'loss_cause')},
            },
        ),
        migrations.AddField(
            model_name='incident',
            name='causes',
            field=models.ManyToManyField(related_name='incidents', through='incidents.IncidentCause', to='incidents.losscause'),
        ),
        migrations.CreateModel(
            name='IncidentRequiredField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('required', models.BooleanField(default=False)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.incidentstatusref')),
            ],
            options={
                'unique_together': {('status', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='SimplifiedToBaselEventMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False)),
                ('basel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.baseleventtype')),
                ('simplified', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.simplifiedeventtyperef')),
            ],
            options={
                'verbose_name': 'Simplified to Basel Event Map',
                'verbose_name_plural': 'Simplified to Basel Event Maps',
                'unique_together': {('simplified', 'basel')},
            },
        ),
    ]
