# Generated by Django 5.2.7 on 2025-10-15 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='simplified_event_type',
            field=models.ForeignKey(blank=True, help_text='Simplified event type chosen by the employee in UI.', null=True, on_delete=django.db.models.deletion.PROTECT, to='incidents.simplifiedeventtyperef'),
        ),
    ]
