# Generated by Django 5.2.7 on 2025-10-22 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_incident_simplified_event_type'),
        ('references', '0002_baselbusinessline_baseleventtype_businessprocess_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='near_miss',
            field=models.BooleanField(default=False, help_text='Near miss: True/False'),
        ),
        migrations.CreateModel(
            name='AllowedTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='incidents.incidentstatusref')),
                ('role', models.ForeignKey(help_text='The role required to perform this transition.', on_delete=django.db.models.deletion.CASCADE, to='references.role')),
                ('to_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='incidents.incidentstatusref')),
            ],
            options={
                'verbose_name': 'Allowed Workflow Transition',
                'unique_together': {('from_status', 'to_status', 'role')},
            },
        ),
    ]
