# Generated by Django 5.2.7 on 2025-11-07 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_incident_reviewed_by'),
        ('references', '0002_baselbusinessline_baseleventtype_businessprocess_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentEditableField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.role')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.incidentstatusref')),
            ],
            options={
                'verbose_name': 'Editable Incident Field',
                'unique_together': {('status', 'role', 'field_name')},
            },
        ),
    ]
