# Generated by Django 5.2.7 on 2025-11-14 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_incidenteditablefield'),
        ('measures', '0003_measure_notes_measureeditablefield'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.incident')),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measures.measure')),
            ],
            options={
                'unique_together': {('incident', 'measure')},
            },
        ),
        migrations.AddField(
            model_name='incident',
            name='measures',
            field=models.ManyToManyField(blank=True, related_name='incidents', through='incidents.IncidentMeasure', to='measures.measure'),
        ),
    ]
