# Generated by Django 5.2.8 on 2025-11-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0006_incidentmeasure_incident_measures'),
        ('risks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='risks',
            field=models.ManyToManyField(related_name='related_incidents', through='risks.IncidentRisk', to='risks.risk'),
        ),
    ]
