# Generated by Django 5.2.8 on 2025-12-04 02:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0002_baselbusinessline_baseleventtype_businessprocess_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('reference_doc', models.CharField(blank=True, help_text='Link to control procedure document or wiki', max_length=255)),
                ('control_type', models.CharField(choices=[('PREVENTIVE', 'Preventive'), ('DETECTIVE', 'Detective'), ('CORRECTIVE', 'Corrective')], default='PREVENTIVE', max_length=20)),
                ('control_nature', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATED', 'Automated'), ('HYBRID', 'IT-Dependent Manual')], default='MANUAL', max_length=20)),
                ('control_frequency', models.CharField(choices=[('CONTINUOUS', 'Continuous'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUALLY', 'Annually'), ('AD_HOC', 'Ad-hoc - Event Driven')], help_text='How often this control is performed', max_length=20)),
                ('effectiveness', models.SmallIntegerField(blank=True, help_text='Design effectiveness rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this control is currently operational')),
                ('business_process', models.ForeignKey(blank=True, help_text='Primary business process this control applies to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='controls', to='references.businessprocess')),
                ('business_unit', models.ForeignKey(help_text='The unit that owns/operates this control', on_delete=django.db.models.deletion.PROTECT, related_name='controls', to='references.businessunit')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(help_text='User responsible for operating/maintaining this control', on_delete=django.db.models.deletion.PROTECT, related_name='owned_controls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
