# Generated by Django 5.2.9 on 2025-12-14 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0001_initial'),
        ('references', '0002_baselbusinessline_baseleventtype_businessprocess_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='control_level',
            field=models.CharField(choices=[('STANDARD', 'Standard (Organization-wide)'), ('LOCAL', 'Local (Business Unit Specific Implementation)')], default='STANDARD', help_text='STANDARD: Org-wide policy. LOCAL: BU-specific implementation', max_length=20),
        ),
        migrations.AddField(
            model_name='control',
            name='parent_control',
            field=models.ForeignKey(blank=True, help_text='Parent standard if this is a local implementation', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_controls', to='controls.control'),
        ),
        migrations.AlterField(
            model_name='control',
            name='business_unit',
            field=models.ForeignKey(blank=True, help_text='The unit that owns/operates this control', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='controls', to='references.businessunit'),
        ),
    ]
