# Generated by Django 5.2.9 on 2025-12-15 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0002_control_control_level_control_parent_control_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='control',
            options={'ordering': ['-created_at', 'id']},
        ),
    ]
