# Generated by Django 5.2.9 on 2025-12-15 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_baselbusinessline_baseleventtype_businessprocess_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baselbusinessline',
            options={'ordering': ['name', 'id'], 'verbose_name': 'Basel Business Line', 'verbose_name_plural': 'Basel Business Lines'},
        ),
        migrations.AlterModelOptions(
            name='baseleventtype',
            options={'ordering': ['name', 'id'], 'verbose_name': 'Basel Event Type', 'verbose_name_plural': 'Basel Event Types'},
        ),
        migrations.AlterModelOptions(
            name='businessprocess',
            options={'ordering': ['name', 'id'], 'verbose_name': 'Business Process', 'verbose_name_plural': 'Business Processes'},
        ),
        migrations.AlterModelOptions(
            name='businessunit',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name', 'id']},
        ),
    ]
