# Generated by Django 5.2.8 on 2025-11-25 16:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0006_incidentmeasure_incident_measures'),
        ('measures', '0003_measure_notes_measureeditablefield'),
        ('references', '0002_baselbusinessline_baseleventtype_businessprocess_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Risk Categories',
            },
        ),
        migrations.CreateModel(
            name='IncidentRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.incident')),
            ],
            options={
                'verbose_name': 'Incident to Risk Link',
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('inherent_likelihood', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('inherent_impact', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('residual_likelihood', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('residual_impact', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ASSESSED', 'Assessed (Pending Validation)'), ('ACTIVE', 'Active'), ('RETIRED', 'Retired')], default='DRAFT', max_length=20)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('submitted_for_review_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('retirement_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='General notes, comments, or justification for status changes.')),
                ('basel_event_type', models.ForeignKey(blank=True, help_text='The specific Basel category for external reporting.', null=True, on_delete=django.db.models.deletion.PROTECT, to='references.baseleventtype')),
                ('business_process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='references.businessprocess')),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='references.businessunit')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('incidents', models.ManyToManyField(through='risks.IncidentRisk', to='incidents.incident')),
                ('owner', models.ForeignKey(help_text="User responsible for managing this risk's mitigation and review.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_risks', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='references.product')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_risks', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validated_risks', to=settings.AUTH_USER_MODEL)),
                ('risk_category', models.ForeignKey(help_text='Internal risk category.', on_delete=django.db.models.deletion.PROTECT, to='risks.riskcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='incidentrisk',
            name='risk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.risk'),
        ),
        migrations.CreateModel(
            name='RiskCategoryToBaselEventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basel_event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.baseleventtype')),
                ('risk_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.riskcategory')),
            ],
            options={
                'verbose_name': 'Risk Category to Basel Event Type Mapping',
                'unique_together': {('risk_category', 'basel_event_type')},
            },
        ),
        migrations.AddField(
            model_name='riskcategory',
            name='basel_event_types',
            field=models.ManyToManyField(help_text='Which Basel event types are valid for this category', related_name='mapped_risk_categories', through='risks.RiskCategoryToBaselEventType', to='references.baseleventtype'),
        ),
        migrations.CreateModel(
            name='RiskMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measures.measure')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.risk')),
            ],
            options={
                'verbose_name': 'Risk to Measure Link',
                'unique_together': {('risk', 'measure')},
            },
        ),
        migrations.AddField(
            model_name='risk',
            name='measures',
            field=models.ManyToManyField(blank=True, related_name='risks', through='risks.RiskMeasure', to='measures.measure'),
        ),
        migrations.AlterUniqueTogether(
            name='incidentrisk',
            unique_together={('incident', 'risk')},
        ),
    ]
