# Generated by Django 5.2.8 on 2025-12-04 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0001_initial'),
        ('risks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Why is this control applied to this risk? (Mapping logic)')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controls.control')),
                ('linked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_links', to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.risk')),
            ],
            options={
                'verbose_name': 'Risk to Control Link',
                'unique_together': {('risk', 'control')},
            },
        ),
        migrations.AddField(
            model_name='risk',
            name='controls',
            field=models.ManyToManyField(blank=True, related_name='risks', through='risks.RiskControl', to='controls.control'),
        ),
    ]
